name: HEMS.yml

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: |
          docker build -t adouni/homeenergymanagementsystem:latest .
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push adouni/homeenergymanagementsystem:latest
          
  deploy:
    name: Deploy 
    needs: build
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@master
        
        - name: Login to Docker Hub
          uses: docker/login-actions@master
        
          with:
            USERNAME: ${{ secrets.DOCKER_USERNAME }}
            PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        - name: install minikube
          uses: medyagt/setup-minikube@master
          with:
           minikube-version:latest
           
        - name: Start Minikube
          run: |
           minikube start --driver=docker

        - name: Pull Docker Image from Docker Hub
          env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
           docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
           docker pull adouni/homeenergymanagementsystemhems:latest
           minikube image load adouni/homeenergymanagementsystemhems:latest

        - name: Deploy to Minikube
          run: |
           kubectl apply -f homeenergymanagementsystem-deployment.yaml
           kubectl apply -f homeenergymanagementsystem-service.yaml

